<a href="https://colab.research.google.com/github/vaibhav-arde/statWithPython/blob/main/handlingInbalancedDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [9]:
import numpy as np

np.random.seed(123)

# Generate some random numbers
random_numbers = np.random.rand(5)

print(random_numbers)


[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


In [6]:
# [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
# [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]

# [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
# [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
# [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]

#Process to create Inbalanced data set

In [11]:
#Create a dtaframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [12]:
n_class_0, n_class_1

(900, 100)

In [16]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [17]:
df = pd.concat([class_0, class_1]).reset_index(drop =True)

In [18]:
df.head()

feature_1  feature_2  target
0   0.447148  -1.119786       0
1   1.016458  -0.003824       0
2   1.670488   0.901543       0
3   0.560869   0.118748       0
4  -0.566060  -0.087810       0

In [19]:
df['target'].value_counts()

0    900
1    100
Name: target, dtype: int64

#Process to upsample

In [34]:
#this is common for upsample and downsample
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [23]:
df_minority.head()

feature_1  feature_2  target
900   2.325982   3.053464       1
901   2.720791   2.867850       1
902   1.959348   2.881091       1
903   1.516523   4.403762       1
904   2.096614   3.360065       1

In [24]:
df_majority.head()

feature_1  feature_2  target
0   0.447148  -1.119786       0
1   1.016458  -0.003824       0
2   1.670488   0.901543       0
3   0.560869   0.118748       0
4  -0.566060  -0.087810       0

In [36]:
#This is common step for upsample and downsample
from sklearn.utils import resample

In [26]:
df_minority_upsample = resample(df_minority,
                                replace=True, #Sample with replacement
                                n_samples=len(df_majority), # to match majority class
                                random_state=42
                                )

In [27]:
df_minority_upsample.shape

(900, 3)

In [28]:
df_minority_upsample['target'].value_counts()

1    900
Name: target, dtype: int64

In [38]:
df_upSampled = pd.concat([df_majority, df_minority_upsample])

In [39]:
df_upSampled['target'].value_counts()

0    900
1    900
Name: target, dtype: int64

In [40]:
df_upSampled.shape

(1800, 3)

#Process To DownSampling

In [49]:
df_majority_downsample = resample(df_majority,
                                replace=False, #Sample with replacement
                                n_samples=len(df_minority), # to match majority class
                                random_state=42
                                )

In [50]:
df_majority_downsample.shape

(100, 3)

In [51]:
df_majority_downsample['target'].value_counts()

0    100
Name: target, dtype: int64

In [52]:
df_downSampled = pd.concat([df_minority, df_majority_downsample])

In [53]:
df_downSampled['target'].value_counts()

1    100
0    100
Name: target, dtype: int64